// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBES27QcrofdjKQ0Wo091suw_g8-uEIQ',
    appId: '1:17875898288:web:93f32f6cea70ef50c25075',
    messagingSenderId: '17875898288',
    projectId: 'finstagram-test',
    authDomain: 'finstagram-test.firebaseapp.com',
    storageBucket: 'finstagram-test.appspot.com',
    measurementId: 'G-SS6L6SNJS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDnuAAC0A9zSQl9KpU2DAGh7BOLMGqTWM',
    appId: '1:17875898288:android:8721e75b74a8f5b2c25075',
    messagingSenderId: '17875898288',
    projectId: 'finstagram-test',
    storageBucket: 'finstagram-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiKOHc6ck3ZwLuvjvPvFAgU2NdPu8Z30I',
    appId: '1:17875898288:ios:d0c181af56252069c25075',
    messagingSenderId: '17875898288',
    projectId: 'finstagram-test',
    storageBucket: 'finstagram-test.appspot.com',
    iosBundleId: 'com.example.goMoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiKOHc6ck3ZwLuvjvPvFAgU2NdPu8Z30I',
    appId: '1:17875898288:ios:65e45bd4ceaaf1cbc25075',
    messagingSenderId: '17875898288',
    projectId: 'finstagram-test',
    storageBucket: 'finstagram-test.appspot.com',
    iosBundleId: 'com.example.goMoon.RunnerTests',
  );
}
